# Generated by Django 5.1.3 on 2024-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('LLC', 'Limited Liability Company'), ('CORP', 'Corporation'), ('SOLE', 'Sole Proprietorship'), ('PART', 'Partnership')], max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('NCR', 'National Capital Region'), ('CAR', 'Cordillera Administrative Region'), ('Region I', 'Ilocos Region'), ('Region II', 'Cagayan Valley'), ('Region III', 'Central Luzon'), ('Region IV-A', 'CALABARZON'), ('Region IV-B', 'MIMAROPA Region'), ('Region V', 'Bicol Region'), ('Region VI', 'Western Visayas'), ('Region VII', 'Central Visayas'), ('Region VIII', 'Eastern Visayas'), ('Region IX', 'Zamboanga Peninsula'), ('Region X', 'Northern Mindanao'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKSARGEN'), ('Region XIII', 'Caraga'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=20)),
            ],
        ),
    ]
